[default]
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 1000000
remappings = ["ds-test/=lib/ds-test/src/", "solmate/=lib/solmate/src/", "base64/=lib/base64/", "gsn/=lib/gsn/packages/contracts/src/"]
verbosity = 1